<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'HibpCheck\\' => array($baseDir . '/src'),
    'Dxw\\Result\\' => array($vendorDir . '/dxw/result/src'),
    'Dxw\\Iguana\\' => array($vendorDir . '/dxw/iguana/src'),
    'Aura\\Autoload\\' => array($vendorDir . '/aura/autoload/src'),
);
