<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit93dc33cbba0bc6ab43aa60f4d30224dd
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PasswordCheck\\' => 14,
        ),
        'D' => 
        array (
            'Dxw\\Result\\' => 11,
            'Dxw\\Iguana\\' => 11,
        ),
        'A' => 
        array (
            'Aura\\Autoload\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PasswordCheck\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
        'Dxw\\Result\\' => 
        array (
            0 => __DIR__ . '/..' . '/dxw/result/src',
        ),
        'Dxw\\Iguana\\' => 
        array (
            0 => __DIR__ . '/..' . '/dxw/iguana/src',
        ),
        'Aura\\Autoload\\' => 
        array (
            0 => __DIR__ . '/..' . '/aura/autoload/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit93dc33cbba0bc6ab43aa60f4d30224dd::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit93dc33cbba0bc6ab43aa60f4d30224dd::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
